### ISSUE TITLE
Why reinvent the wheel?

### ISSUE THREAD

**Issue by kfur** [ndey96/youtube-recommended-blocker#1]
There is convenient adblock plus [filter](https://youtube.adblockplus.me) that do it but leave button to disclose recommendations.

**Comment by jordikitto** [comment]
Some of us don't use Adblock...

**Comment by kfur** [comment]
@jordikitto ok, I understand, but there is [stylish](https://safari-extensions.apple.com/details/?id=com.sobolev.stylish-5555L95H45) extension.
